/**
 * Sample row data seeded into the 6 default CRM boards for a fresh org.
 *
 * Ported verbatim from legacy `backend/src/dummydata/index.js` (dummyDataSets
 * + dummyDatBoard). Legacy addDummyData() looped 10 times and for each board
 * picked values[i % values.length], so even when a dataset had fewer than 10
 * rows the org still ended up with 10 board_items per board. Opt-out had
 * dummy rows defined but legacy explicitly skipped it (see the `boardNames`
 * filter in addDummyData), so we mirror that: rows are present here for
 * completeness but seedDefaults never inserts them.
 *
 * Each "values" array's element ORDER must match the `fields` order on the
 * matching DefaultBoardTemplate from `default-boards.template.ts` — the
 * seeder zips them by index.
 */

export interface SeedBoardDataset {
  boardName: string;
  values: string[][];
}

export const DUMMY_DATA_SETS: SeedBoardDataset[] = [
  {
    boardName: "Contacts",
    values: [
      [
        "Eleanor Finch",
        "eleanor.finch@soaring.co",
        "1 (206) 555-0101",
        "Soaring Skylines Airlines",
        "Marketing Director",
        "Seattle, Washington",
        "08/15/1986",
        "Female",
        "Ms.",
        "1 (206) 555-0101",
        "Ellie@1234",
        "Ellietravelling",
        "Ellietravelist",
        "12/12/2023",
        "01/01/2024",
        "Prospect",
        "This is a sample data",
        null,
      ],
      [
        "Valentina Rossi",
        "valentina.rossi@terracotta.co",
        "393218459267",
        "Terracotta Designs",
        "Lead Architect",
        "Florence, Italy",
        "05/10/1992",
        "Female",
        "Ms.",
        "393218459267",
        "Rossi.vale",
        "vale.rossi",
        "rossilovedesign",
        "12/30/2023",
        "12/30/2023",
        "Contact",
        "This is a sample data",
        null,
      ],
      [
        "Omar Sharif",
        "omar.sharif@cognitionlab.co",
        "6011-8976541",
        "Cognition Lab",
        "Robotics Engineer",
        "Petaling Jaya, Malaysia",
        "03/22/1979",
        "Male",
        "Dr.",
        "6011-8976541",
        "OmarSharif888",
        "OmarSharif888",
        "robot.omarlife",
        "06/11/2023",
        "11/17/2023",
        "Identified Lead",
        "This is a sample data",
        "default second option",
      ],
      [
        "Chen Lee",
        "chen_lee@qq.com",
        "862887870912",
        "Zen Electronics",
        "Sales Manager",
        "Shenzhen, China",
        "02/02/1968",
        "Male",
        "Mr.",
        "862887870912",
        "wxid_5uofn5hj6k",
        "u354a7654b8954c65",
        "chen.lee.zen.electronics",
        "08/23/2022",
        "09/16/2023",
        "Customer",
        "This is a sample data",
        null,
      ],
      [
        "Evelyn Sato",
        "evelyn.sato@inkwell.co",
        "815088158553",
        "Inkwell Studios",
        "Public Relations Specialist",
        "Okinawa, Japan",
        "04/25/1975",
        "Female",
        "Miss.",
        "815088158553",
        "wxid_45hkj2jhhd",
        "satoevelyn238",
        "designevelyn_sato",
        "10/24/2023",
        "10/30/2023",
        "Disqualified",
        "This is a sample data",
        null,
      ],
      [
        "Luna Garcia",
        "spice.lunagracia@gmail.com",
        "91 888 555 0101",
        "Spice Symphony",
        "Head Chef",
        "Mumbai, India",
        "06/01/1980",
        "Female",
        "Ms.",
        "91 888 555 0101",
        "Spice.Lunagracia61",
        "luna.spices",
        "lunagracia.spice",
        "11/19/2023",
        "01/02/2024",
        "Contact",
        "This is a sample data",
        null,
      ],
      [
        "Priya Singh",
        "priya.singh@starlight.co",
        "61390466102",
        "Starlight Observatory",
        "Freelancer (Comic)",
        "Sydney, Australia",
        "12/08/1988",
        "Neutral",
        "Mx.",
        "61290598643",
        "PriyaStargazer",
        "PriyaStargazer837",
        "Priya.StarObservator",
        "12/28/2023",
        "01/05/2024",
        "Advocator",
        "This is a sample data",
        null,
      ],
      [
        "Jamie Kim",
        "kim.jamie@ecotech.co",
        "823157375855",
        "EcoTech Solutions",
        "Solution Manager",
        "Seoul, South Korea",
        "03/14/1996",
        "Male",
        "Mr.",
        "823157375855",
        "wxid_1hjg34j5jjkf",
        "Jamie.Kim489",
        "Jamie.ecotech",
        "04/30/2021",
        "06/12/2023",
        "Customer",
        "This is a sample data",
        null,
      ],
      [
        "Alistair Campbell",
        "campbell.alistair345@gmail.com",
        "441371412152",
        "The Floury Hand",
        "Baker and Owner",
        "Brighton, England",
        "03/06/1970",
        "Male",
        "Mr.",
        "441371412152",
        "FlouryHand.Brighton",
        "FlouryHand.Brighton",
        "FlouryHand.Brighton",
        "07/03/2023",
        "11/14/2023",
        "Prospect",
        "This is a sample data",
        null,
      ],
      [
        "Nneka Okafor",
        "okafor.nnekadesign@gmail.com",
        "254103860830",
        "Ikat Elegance",
        "Fashion designer and founder",
        "Nairobi, Kenya",
        "09/02/1990",
        "Female",
        "Mrs.",
        "254103860830",
        "wxid_45jghgk2b5",
        "u367a7758k8954z65",
        "ikat.elegance",
        "01/03/2024",
        "01/03/2024",
        "Contact",
        "This is a sample data",
        null,
      ],
    ],
  },
  {
    boardName: "Companies",
    values: [
      [
        "Code and Caffeine",
        "Software Development and Solutions",
        "10-50",
        "Bohol Island, Philippines",
        "1213 Mahogany Drive, Purok Pag-asa, Davao City, Bohol Island",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "07/04/2020",
        "Identified Lead",
      ],
      [
        "Soaring Skylines Airlines",
        "Aviation",
        "1000+",
        "Queenstown, New Zealand",
        "1819 Kakapo Crescent, Wanaka, South Island, New Zealand",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "10/31/2021",
        "Customer",
      ],
      [
        "Green Hope Foundation",
        "Non-Profit Organization",
        "1000+",
        "Austin, Texas",
        "87 Sunset Point Road, Salty Shores, TX 79910",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "03/17/2022",
        "Advocator",
      ],
      [
        "Local Foodie Finds",
        "Food Blogging",
        "1-10",
        "Seoul, South Korea",
        "55 Wishing Lantern Drive, Seoul Forest Park 02137",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "11/27/2020",
        "Contact",
      ],
      [
        "Upcycled Artist Collective",
        "Art and Design",
        "50-250",
        "Lijiang Old Town, China",
        "101 Caravanserai Square, Lijiang 710061",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "05/24/2022",
        "Disqualified",
      ],
      [
        "Moonandink",
        "Book and stationery",
        "10-50",
        "Edinburgh, Scotland",
        "32 Thistle Lane, Castlehill, Dunfermline, KY12 7HA",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "01/03/2021",
        "Customer",
      ],
      [
        "Brushstrokes and Dreams",
        "Online Education",
        "50-250",
        "San Francisco, California",
        "42 Lombard Street, San Francisco, CA 94133",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "08/12/2022",
        "Retention",
      ],
      [
        "Emberwood Crafts",
        "Handmade Crafts and Woodworking",
        "50-250",
        "Mumbai, India",
        "The Coconut Grove, Alappuzha, Kerala 688001",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "09/02/2022",
        "Advocator",
      ],
      [
        "The Wandering Whisk",
        "Food Truck and Catering",
        "50-250",
        "Bangkok, Thailand",
        "15 Lanna Lane, Bangkok, 50000",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "01/21/2023",
        "Prospect",
      ],
      [
        "Urban Oasis",
        "Sustainable Design and Architecture",
        "250-1000",
        "Singapore",
        "8 Boat Quay, Singapore 048652",
        "https://www.google.com/",
        "https://www.linkedin.com/",
        "This is a sample data",
        "02/14/2023",
        "Unidentified Lead",
      ],
    ],
  },
  {
    boardName: "Opportunities",
    values: [
      ["Eleanor Finch", "Prospecting", "Mr.iMBrace", "Medium", "9999", "01/01/2024", "This is a sample data", "12/12/2023"],
      ["Valentina Rossi", "Qualified", "Ms.iMBrace", "Medium", "9999", "12/30/2023", "This is a sample data", "12/30/2023"],
      ["Omar Sharif", "Initial Meeting", "Ms.iMBrace", "High", "9999", "11/17/2023", "This is a sample data", "06/11/2023"],
      ["Chen Lee", "Proposal", "Mr.iMBrace", "High", "9999", "09/16/2023", "This is a sample data", "08/23/2022"],
      ["Evelyn Sato", "Negotiation", "Mr.iMBrace", "Very High", "9999", "10/30/2023", "This is a sample data", "10/24/2023"],
      ["Luna Garcia", "Closing", "Ms.iMBrace", "Medium", "9999", "01/02/2024", "This is a sample data", "11/19/2023"],
      ["Priya Singh", "Retention", "Ms.iMBrace", "Medium", "9999", "01/05/2024", "This is a sample data", "12/28/2023"],
      ["Jamie Kim", "Disqualified", "Mr.iMBrace", "Low", "9999", "06/12/2023", "This is a sample data", "04/31/2021"],
      ["Alistair Campbell", "Initial Meeting", "Mr.iMBrace", "Low", "9999", "11/14/2023", "This is a sample data", "07/03/2023"],
      ["Nneka Okafor", "Negotiation", "Ms.iMBrace", "High", "9999", "01/03/2024", "This is a sample data", "01/03/2024"],
    ],
  },
  {
    boardName: "Tasks",
    values: [
      ["Eleanor Finch", "This is a sample data", "Backlogs", "Mr.iMBrace", "Medium", "01/01/2024", "https://www.google.com/", "12/12/2023"],
      ["Valentina Rossi", "This is a sample data", "To-Dos", "Ms.iMBrace", "Medium", "12/30/2023", "https://www.google.com/", "12/30/2023"],
      ["Omar Sharif", "This is a sample data", "In-Progress", "Ms.iMBrace", "High", "11/17/2023", "https://www.google.com/", "06/11/2023"],
      ["Chen Lee", "This is a sample data", "In-Review", "Mr.iMBrace", "High", "09/16/2023", "https://www.google.com/", "08/23/2022"],
      ["Evelyn Sato", "This is a sample data", "Done", "Mr.iMBrace", "Very High", "10/30/2023", "https://www.google.com/", "10/24/2023"],
      ["Luna Garcia", "This is a sample data", "Backlogs", "Ms.iMBrace", "Medium", "01/02/2024", "https://www.google.com/", "11/19/2023"],
      ["Priya Singh", "This is a sample data", "To-Dos", "Ms.iMBrace", "Medium", "01/05/2024", "https://www.google.com/", "12/28/2023"],
      ["Jamie Kim", "This is a sample data", "In-Progress", "Mr.iMBrace", "Low", "06/12/2023", "https://www.google.com/", "04/31/2021"],
      ["Alistair Campbell", "This is a sample data", "In-Review", "Mr.iMBrace", "Low", "11/14/2023", "https://www.google.com/", "07/03/2023"],
      ["Nneka Okafor", "This is a sample data", "Done", "Ms.iMBrace", "High", "01/03/2024", "https://www.google.com/", "01/03/2024"],
    ],
  },
  {
    boardName: "Product",
    values: [
      ["TerraFirma Backpack", "Adventure travel backpack", "€149", "Euros", "Development"],
      ["Cumbia Caliente Coffee", "Latin American single-origin coffee", "$24.99 USD", "US Dollars", "On Shelf"],
      ["Nomad Pro Wireless Headphones", "Noise-canceling headphones", "£199.99", "British Pounds", "Marketing"],
      ["Stardust Projector Nightlight", "Galaxy light projector", "CAD $69.95", "Canadian Dollars", "Prototyping"],
      ["Spice Symphony Hot Sauce", "Small-batch gourmet hot sauces", "AUD $39.99", "Australian Dollars", "Launch"],
      ["Zen Harmony Bamboo Diffuser", "Ultrasonic essential oil diffuser", "¥2980 JPY", "Japan Yen", "Production"],
      ["Wildscape Wildlife Camera", "Motion-activated camera", "R$799.00 BRL", "Brazil", "On Shelf"],
      ["Whispering Waves", "Self-Watering Plant Pot", "€39.95", "Euros", "Ideation"],
      ["Pocket Pal", "Portable Language Translator", "¥4,980 JPY", "Japan Yen", "Improvement"],
      ["Pocket Picasso", "Miniature Sketchbook and Pen Set", "₩19,900", "South Korea Won", "Launch"],
    ],
  },
];

/**
 * Names of boards that get sample rows seeded. Legacy addDummyData explicitly
 * filtered to this set even though Opt-out also had dummy rows defined.
 */
export const BOARDS_WITH_SAMPLE_ROWS = new Set([
  "Contacts",
  "Companies",
  "Opportunities",
  "Tasks",
  "Product",
]);

/**
 * "Demo Board" is a 7th board appended after the 6 defaults. It has 2 fields
 * (Name, Email) and is seeded with rows that match the legacy
 * `addDummyDataBoard` behaviour. The legacy code had a bug — boardItems was
 * declared once but pushed-and-insertMany'd on every iteration, so a 4-row
 * `values` array produced 1+2+3+4 = 10 inserts (with duplicates). Sandbox
 * orgs end up with exactly 10 items per Demo Board because of this.
 *
 * We reproduce the same final count here for parity (10 items per Demo
 * Board), but without the duplicates: cycle the 4 base values across 10
 * inserts the same way the other boards do.
 */
export const DEMO_BOARD_NAME = "Demo Board";
export const DEMO_BOARD_DESCRIPTION = "This is a demo board";

export const DEMO_BOARD_VALUES: string[][] = [
  ["Eleanor Finch", "sample@gmail.com"],
  ["No Name", "sample1@gmail.com"],
  ["Sample Name", "sample2@gmail.com"],
  ["Tony L", "sample3@gmail.com"],
];

/** Number of board_items legacy seeded per board (Contacts, Companies, ...). */
export const SAMPLE_ROWS_PER_BOARD = 10;
